"""Order-related data types — UnifiedOrder, OrderModification, OrderResult, OrderRecord."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

from unified_trading_execution.types.enums import OrderSide, OrderStatus, OrderType, TimeInForce
from unified_trading_execution.types.instrument import Instrument


@dataclass(frozen=True, slots=True)
class TpSlAttachment:
    """Take-profit or stop-loss attached to an order at placement."""

    trigger_price: Decimal
    limit_price: Decimal | None = None  # None = market execution when triggered

    def __post_init__(self) -> None:
        if self.trigger_price <= 0:
            raise ValueError(f"trigger_price must be > 0, got {self.trigger_price}")
        if self.limit_price is not None and self.limit_price <= 0:
            raise ValueError(f"limit_price must be > 0, got {self.limit_price}")


@dataclass(slots=True)
class UnifiedOrder:
    """An order request before dispatch — validated at construction.

    client_order_id: generated by core (UUID7) if not user-supplied.
    A user-supplied ID is validated for uniqueness against the state store.
    """

    instrument: Instrument
    order_type: OrderType
    side: OrderSide
    quantity: Decimal
    time_in_force: TimeInForce
    client_order_id: str | None = None
    price: Decimal | None = None  # LIMIT, STOP_LIMIT
    stop_price: Decimal | None = None  # STOP, STOP_LIMIT
    reduce_only: bool = False
    client_tag: str | None = None  # user reference, never read by engine
    take_profit: TpSlAttachment | None = None
    stop_loss: TpSlAttachment | None = None

    def __post_init__(self) -> None:
        # Price required for LIMIT and STOP_LIMIT
        if self.order_type in (OrderType.LIMIT, OrderType.STOP_LIMIT):
            if self.price is None:
                raise ValueError(f"price is required for {self.order_type}")
        # Stop price required for STOP and STOP_LIMIT
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT):
            if self.stop_price is None:
                raise ValueError(f"stop_price is required for {self.order_type}")
        # Quantity must be positive
        if self.quantity <= 0:
            raise ValueError(f"quantity must be > 0, got {self.quantity}")
        # Price must be > 0 when present
        if self.price is not None and self.price <= 0:
            raise ValueError(f"price must be > 0, got {self.price}")
        if self.stop_price is not None and self.stop_price <= 0:
            raise ValueError(f"stop_price must be > 0, got {self.stop_price}")


@dataclass(slots=True)
class OrderModification:
    """A request to modify an existing order. At least one optional field must be set."""

    client_order_id: str
    price: Decimal | None = None
    stop_price: Decimal | None = None
    quantity: Decimal | None = None
    take_profit: TpSlAttachment | None = None
    stop_loss: TpSlAttachment | None = None

    def __post_init__(self) -> None:
        if self.price is None and self.stop_price is None and self.quantity is None and self.take_profit is None and self.stop_loss is None:
            raise ValueError("OrderModification must set at least one field to modify")


@dataclass(frozen=True, slots=True)
class OrderResult:
    """The result of an order operation — returned by place, modify, cancel, and query."""

    client_order_id: str
    platform_order_id: str | None  # None only if rejected before platform assigned an ID
    status: OrderStatus
    filled_quantity: Decimal
    average_fill_price: Decimal | None  # None until first fill
    created_at: datetime  # UTC, timezone-aware
    updated_at: datetime  # UTC, timezone-aware

    def __post_init__(self) -> None:
        if self.created_at.tzinfo is None:
            raise ValueError("created_at must be timezone-aware (UTC)")
        if self.updated_at.tzinfo is None:
            raise ValueError("updated_at must be timezone-aware (UTC)")


@dataclass(frozen=True, slots=True)
class OrderRecord:
    """The full auditable lifecycle of one order — persisted in the state store.

    Combines all fields from UnifiedOrder plus all fields from OrderResult
    plus the correlation_id for distributed tracing.
    """

    # From UnifiedOrder
    instrument: Instrument
    order_type: OrderType
    side: OrderSide
    quantity: Decimal
    time_in_force: TimeInForce
    client_order_id: str
    price: Decimal | None
    stop_price: Decimal | None
    reduce_only: bool
    client_tag: str | None
    take_profit: TpSlAttachment | None
    stop_loss: TpSlAttachment | None

    # From OrderResult
    platform_order_id: str | None
    status: OrderStatus
    filled_quantity: Decimal
    average_fill_price: Decimal | None

    # Lifecycle
    correlation_id: str
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class FillRecord:
    """A single fill against an order — persisted in the state store (Section 17.11)."""

    client_order_id: str
    platform_fill_id: str
    instrument: Instrument
    fill_quantity: Decimal
    fill_price: Decimal
    fill_timestamp: datetime
    fee_currency: str | None
    fee_amount: Decimal | None
    correlation_id: str

    def __post_init__(self) -> None:
        if self.fill_timestamp.tzinfo is None:
            raise ValueError("fill_timestamp must be timezone-aware (UTC)")
        if self.fill_quantity <= 0:
            raise ValueError(f"fill_quantity must be > 0, got {self.fill_quantity}")
        if self.fill_price <= 0:
            raise ValueError(f"fill_price must be > 0, got {self.fill_price}")
